# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db84aeaf28b7161cc6c25c4d93cf7abd724a70416e03ef95c3b411fcc20af980bf192a00ec7e99bc314b382b70022f04c0db00f12ef4a3a939a6f88dabef71cf

test:
  secret_key_base: 3a1a07016a7ea334639dd2e5d0d28bac86d28cd2c2ec9324390b312aa1831fc621c9dfcd9247e89781e2eb1504c2a6d11c9995c91a8f031cb6d4bbdc101832c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
